### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by nenti** [SC5/serverless-jest-plugin#1]
TypeError: Cannot read property 'bind' of undefined

      at Runtime._createRuntimeFor (node_modules\serverless-jest-plugin\node_modules\jest-runtime\build\index.js:709

Serverless Version 1.8.0

**Comment by laardee** [comment]
@nenti thanks for reporting the issue. I tried to reproduce the issue with Serverless 1.8.0 and several Node versions, but couldn't. What's your Node version and OS? Are you running `sls invoke test` when the issue appears?

**Comment by pinalbhatt** [comment]
I am also getting similar error.
`
 $ sls invoke test 
 FAIL  __tests__/functions/demo.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'bind' of undefined
      
      at Runtime._createRuntimeFor (node_modules/serverless-jest-plugin/node_modules/jest-runtime/build/index.js:709:52)
      at process._tickDomainCallback (internal/process/next_tick.js:135:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.059s
Ran all test suites.
`
serverless-jest-plugin version "^0.1.3"
sls version 1.12.1
Node Version 6.10.2
OS: mac os x 10.12.4

**Comment by pinalbhatt** [comment]
not sure but i think issue is related to versions of jest/jest-cli.  this package is using 18.1.0 and i also have latest jest 19.x installed.
https://github.com/facebook/jest/issues/3114

**Comment by wajih123** [comment]
create a constructor in the class and initial your function for exemple:
 constructor() {
                         super();
                         this.handleSubmit = this.handleSubmit.bind(this)
                           
                      }

**Comment by vaibhav-systango** [comment]
@nenti any updates?

**Comment by nenti** [comment]
@vaibhav-systango I don't use `sls invoke test` and run with plain `jest`. Working just fine, although you can't execute tests to remote systems this way.
